### ISSUE TITLE
Error when trying to load Altiverb 7

### ISSUE THREAD

**Issue by devnix** [osxmidi/LinVst-X#2]
Please, make me know if I can provide you more information.

![image](https://user-images.githubusercontent.com/1777519/71684491-eeeb5a80-2d95-11ea-906c-6347e491f587.png)

This is the output of `lin-vst-server-x.exe.so`

```
Loading  /home/devnix/.wine/drive_c/Program Files/Steinberg/VSTPlugins/Audio Ease/Altiverb 7.dll
0009:fixme:ver:GetCurrentPackageId (0x228910 (nil)): stub
0009:fixme:heap:RtlSetHeapInformation 0x10000 0 0x229740 4 stub
0043:fixme:msvcrt:MSVCRT__stdio_common_vsprintf_s options 24 not handled
MplugInstanceErr
Load Error
0009:fixme:win:RegisterTouchWindow (0xc0072 00000002): stub
0009:fixme:win:RegisterTouchWindow (0xd0070 00000002): stub
```

In general, it feels way more performant than LinVst, and it doesn't have some keyboard/mouse glitches that I suffered with LinVst (for example, clicking or dragging with the Ctrl key)

**Comment by osxmidi** [comment]
If you can test it with TestVst and get an error then it's Wine not being able to handle it for some reason.

If you run TestVst from a terminal and look at the output then sometimes there can be an unimplemented function error in some dll and that dll can be overriden and then see what happens.

**Comment by devnix** [comment]
This is all the output I get:

```
002a:err:plugplay:load_function_driver AddDevice failed for driver L"winebus", status 0xc0000002.
0040:err:winsock:WSAIoctl -> SIO_ADDRESS_LIST_CHANGE request failed with status 0x2733
LinVst Vst Test
AEffectError
$
wine: Unhandled page fault on write access to 0x085ffa68 at address 7BC68944 (thread 001f), starting debugger...
001f:err:seh:start_debugger Couldn't start debugger L"winedbg --auto 26 328" (1115)
Read the Wine Developers Guide on how to set up winedbg or another debugger
```

**Comment by osxmidi** [comment]
There are Wine errors.

Altiverb 7 seems to use ilok and I don't think that's going to run with Wine.

Altiverb 7 requires the iLok USB Key (2nd generation or newer).

**Comment by keybreak** [comment]
@osxmidi 
Actually, even if you will be able to "bypass" iLok - you still won't be able to initialize / load Altiverb 7, i think it's d2d1.dll problem...

@devnix
> In general, it feels way more performant than LinVst, and it doesn't have some keyboard/mouse glitches that I suffered with LinVst (for example, clicking or dragging with the Ctrl key)

Huh...Really? Should try it out :+1: 

> Plugins running in one process are not sandboxed, so if one plugin crashes then the whole lot might crash.

Although that part doesn't sound very happy :smile:
