### ISSUE TITLE
LinVst-X Server not closing on DAW close and using high CPU vs LinVST

### ISSUE THREAD

**Issue by klangfarben1** [osxmidi/LinVst-X#3]
This applies only to LinVST-X not LinVST. I have only tested the VST2X version not VST3X.

On First load of a LinVST-X wrapped plugin, LinVST Server takes 10% of my CPU. A LinVST wrapped plugin only uses about 1% of my CPU on first load. Subsequent loads of LinVST-X plugins do not use much more CPU, but the CPU usage compared to loading even the same plugin wrapped as LinVST instead of LinVST-X uses 10 times the CPU which seems pretty odd.

Also, when closing the DAW (Reaper 6.05), LinVST Server-X does not close and continues to use 10 percent of the CPU. When using the regular LinVST Server, it closes as expected and does not continue to take up CPU.

This is on Manjaro Linux with 5.5.8 Kernel and Wine Staging 5.3.1

**Comment by osxmidi** [comment]
I'll look into it.

The server should be about 1%.

Htop has some issues with Wine I think, and tends to report the wrong values, the task manager is more accurate from my experience.

The server doesn't shut down, it runs in the background but it's process can be killed.

**Comment by klangfarben1** [comment]
Thanks! I'm using Ksysguard to monitor the CPU which has been pretty accurate for me. I think it is a legit CPU usage as my thermal fans also kick in.

**Comment by osxmidi** [comment]
This is what I get on Manjaro with LinVst-X idling in the background.

![linx](https://user-images.githubusercontent.com/26504179/77078890-50dd6700-6a4b-11ea-809d-38cf33619d8c.png)

![linx2](https://user-images.githubusercontent.com/26504179/77079122-a31e8800-6a4b-11ea-89af-951831c330b2.png)

**Comment by klangfarben1** [comment]
Here are 3 screenshots for you. The first is LinVST Server-X after opening a Kontakt and then removing the plugin (idle). It opens and stays at 10 percent even after removing the plugin.

The second screenshot is of both LinVST Server-X and LinVST Server on opening a plugin. LinVST Server (not X) does open at 1 percent usage as you say. LinVST Server-X opens at 9-10 percent.

The third screenshot is after Reaper has completely quit. Regular LinVST Server closes as expected and is no longer listed as a running process. LinVST Server-X however, stays running and continues to take up 10 percent CPU even though Reaper is no longer a running process. Hope this helps you to narrow the issue down.

LinVST Server-X after opening and removing Kontakt:
![linx](https://s3.amazonaws.com/TLMusic/Reaper/LinVST/Reaper+LinVSTX.png)

LinVST Server-X and LinVST Server after plugin open:
![linx2](https://s3.amazonaws.com/TLMusic/Reaper/LinVST/Reaper+LinVST.png)

LinVST Server-X after Reaper quit:
![linx3](https://s3.amazonaws.com/TLMusic/Reaper/LinVST/LinVSTX+w+Reaper+Quit.png)

**Comment by osxmidi** [comment]
As you can see, I'm getting less than 1% cpu when the LinVst-X server is idle and you seem to be getting around 10% for some reason which I'm not sure about, maybe it's because of some component of Kontakt.

It should be less than 1% cpu when the LinVst-X server is idle (no plugin loaded).

The LinVst-X server does not quit (once it's started) unless it is killed because that allows for very fast (future) plugin loading.

I'm using Manjaro with Wine Staging 5.3 and I've tested LinVst-X on i7's and dual core cpu's and on multiple distros, Manjaro/Debian/Ubuntu.

**Comment by osxmidi** [comment]
I tested the Kontakt 6 demo and loaded the Salamander Grand Piano Disk Streaming nki and played something and then unloaded Kontakt and the LinVst-X server went down to 1% or lower and the same when Reaper is closed.

**Comment by osxmidi** [comment]
Are you using wine-rt?

**Comment by klangfarben1** [comment]
I'm on Wine Staging 5.4, no overrides. Also removed my Wine folder and started fresh. Same numbers though.

**Comment by klangfarben1** [comment]
No, I'm using Wine Staging 5.4 no overrides.

**Comment by klangfarben1** [comment]
Also, the numbers on LinVST Server (not X) look perfectly fine. Same as yours. It's only with LinVST Server X that this is happening.

**Comment by osxmidi** [comment]
Yes, I'm just talking about LinVst-X and not LinVst.

What happens (after a reboot) if you load and then load another plugin instead of Kontakt (don't load Kontakt at all), what is the cpu usage of the LinVst-X server when that plugin is removed?

**Comment by klangfarben1** [comment]
Same thing unfortunately. I tried with Klanghelm MJUCjr (free plugin) which has worked without issue in regular LinVST previously. Open blank Reaper project, load plugin and then remove plugin. Here is the usage from ksysguard.

![linx](https://s3.amazonaws.com/TLMusic/Reaper/LinVST/LinVSTX+No+Kontakt.png)

Could this possibly be related to using Jack for the audio driver? Reaper does not list my hardware as an ALSA device even though it is recognized fine in other apps as an ALSA device. Jack RT CPU usage is extremely low and I'm testing with literally 1 audio track so I don't think it would have much effect on CPU. And again, LinVST works fine, just not LinVST-X.

Or could it be related to kernel version? I'm currently using stock Manjaro 5.5.

**Comment by osxmidi** [comment]
I don't know.

It would be useful if I could reproduce it, so that I could track down what it is but I can't reproduce it.

**Comment by keybreak** [comment]
Could it be KDE / kwin specific probably?
Manjaro != Manjaro :smile:
