### ISSUE TITLE
Just want to say WOW.

### ISSUE THREAD

**Issue by 38github** [osxmidi/LinVst-X#4]
I used Carla and its VST bridge with a windows x64 vst and got severe xruns at 64 samples, better but still unusable at 128 samples. With the precompiled (buster) linvst I can use the same vst at 64 samples without any xruns. Amazing!

**Comment by osxmidi** [comment]
> I used Carla and its VST bridge with a windows x64 vst and got severe xruns at 64 samples, better but still unusable at 128 samples. With the precompiled (buster) linvst I can use the same vst at 64 samples without any xruns. Amazing!

Hi,
Thanks for the feedback.

**Comment by 38github** [comment]
It is night and day. I tried the wine and kernels that are patched with esync and fsync but they made no difference using Carla. Using Linvst-x with regular wine and kernel was all that I had to get it to work.

**Comment by vssasks** [comment]
Same experience but with yabridge which consumes 3x more cpu power than linvst. By the way don'tuse jbridge under wine as it also increases3-fold cpu consumption... Make conclusions on your own.

**Comment by vssasks** [comment]
Maybe this developer can make ladspa to vst bridge also? Would be great
