### ISSUE TITLE
LinVst-X with wine-6.3 (Staging)

### ISSUE THREAD

**Issue by Balda789** [osxmidi/LinVst-X#5]
Hello,
I'm trying LinVst-X on Ubuntu 20.04.2 LTS but it doesn't work. Plugin scan in Reaper stoped on "VST Plugin is not responding". Probably it is problem with wine 6.3 (Staging). Downgrade is little bit tricky on ubuntu...

**Comment by osxmidi** [comment]
> Hello,
> I'm trying LinVst-X on Ubuntu 20.04.2 LTS but it doesn't work. Plugin scan in Reaper stoped on "VST Plugin is not responding". Probably it is problem with wine 6.3 (Staging). Downgrade is little bit tricky on ubuntu...

Wine Staging 6.3 has bugs.

The bugs have been fixed so Wine Staging 6.4 will be ok.

You can try to rollback to Wine Staging 6.2 or install Wine Stable 6.

You can go back to Wine Staging when Wine Staging 6.4 comes out.

**Comment by Balda789** [comment]
Yes, with Wine stable 6 it works. Thanks.
