### ISSUE TITLE
LinVst and LinVst-X not working at all.

### ISSUE THREAD

**Issue by p1xlized** [osxmidi/LinVst-X#6]
Hi, I reinstalled my OS and after that bitwig 3.3 doesn't recognize my converted VST. Native VST works well.
Wine version: 6.3
OS: Manjaro gnome edition

Need help asap if it's possible (gotta finish one project)
Thanks

**Comment by p1xlized** [comment]
UPD that's the error 
and the error log.
```
/run/media/alex/a94fcabb-c9ec-4f46-bfb0-7a23bc5ccad7/VST/MT-PowerDrumKit.so
com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: createAEffectInstance returned NULL
-------------------------------------------------------------------
```


![Screenshot from 2021-03-18 19-00-18](https://user-images.githubusercontent.com/72890769/111708419-3257aa80-881c-11eb-8920-5a4409d2b465.png)

**Comment by osxmidi** [comment]
> Hi, I reinstalled my OS and after that bitwig 3.3 doesn't recognize my converted VST. Native VST works well.
> Wine version: 6.3
> OS: Manjaro gnome edition
> 
> Need help asap if it's possible (gotta finish one project)
> Thanks

Wine Staging 6.3 has a bug.

Try downgrading to wine-stable or wine-staging 6.2.

Wine Staging 6.4 (just released) has the bug fixed, so it will be ok.

**Comment by p1xlized** [comment]
I installed 6.4 and 6.2, same error. I tried to reinstall everything(the DAW, wine and linvst), same error.

**Comment by osxmidi** [comment]
Errors like that are quite often when the Daw can't find the lin-vst-server files in /usr/bin.

Try reinstalling LinVst, either the new version or the previous version, I'd try the LinVst version you were using before the system upgrade.

**Comment by p1xlized** [comment]
I tried the last version, and it works, so I guess when I was installing I fucked up something.

Thanks)
