### ISSUE TITLE
confusing build instructions

### ISSUE THREAD

**Issue by asmolcic** [osxmidi/LinVst-X#8]
Hi, I-m having trouble with the install instructions. in the README you say.

> LinVst-X binaries are at https://github.com/osxmidi/LinVst-X/releases
> 
> The usual X11 and Wine dev packages and multilib are needed (details are in the LinVst Make Guide https://github.com/osxmidi/LinVst/tree/master/Make-Guide) then
> 
> make
>
> sudo make install

First, why do I need to use make, etc if I downloaded binaries? Maybe you need to distinguish this in the README file.
Then you continue with:

> See the convert folder Notes on how to make the linvstx.so renaming conversion utilities.

I can't find those notes and i don't know if I do want to make the "linvstx.so renaming conversion utilities". What's that?

Finally, I tried to build the LinVST-X deb-package but I don't understand if I do need both sources since the guide mentions  
folder "64bits-32bits" which is not present in the "X" version? 

I think you should clear this up in the docs. Maybe adding a straightforward step list for each target, for the both versions.

I could help with the docs, maybe. Just need the answers.

**Comment by osxmidi** [comment]
> Hi, I-m having trouble with the install instructions. in the README you say.
> 
> > LinVst-X binaries are at https://github.com/osxmidi/LinVst-X/releases
> > The usual X11 and Wine dev packages and multilib are needed (details are in the LinVst Make Guide https://github.com/osxmidi/LinVst/tree/master/Make-Guide) then
> > make
> > sudo make install
> 
> First, why do I need to use make, etc if I downloaded binaries? Maybe you need to distinguish this in the README file.
> Then you continue with:
> 
> > See the convert folder Notes on how to make the linvstx.so renaming conversion utilities.
> 
> I can't find those notes and i don't know if I do want to make the "linvstx.so renaming conversion utilities". What's that?
> 
> Finally, I tried to build the LinVST-X deb-package but I don't understand if I do need both sources since the guide mentions
> folder "64bits-32bits" which is not present in the "X" version?
> 
> I think you should clear this up in the docs. Maybe adding a straightforward step list for each target, for the both versions.
> 
> I could help with the docs, maybe. Just need the answers.

That's only if someone wants to make LinVst-X.

The binary release contains all that is needed, it just needs to be installed.
