### ISSUE TITLE
Crashes when closing a DAW

### ISSUE THREAD

**Issue by thephantomclarinet** [osxmidi/LinVst-X#9]
Hello,

I have been using LinVst-X a lot recently with some orchestral sample libraries, but have been running into the following issue...

OS: Ubuntu 20.04
DAW: Ardour 6, Reaper
Plugins: Spitfire BBCSO Discover, Native Instruments Kontakt

1) Create a project in the DAW, and load plugins via LinVst-X. Save the project.
2) Try to close the DAW. After a few moments it crashes and displays the 'Not responding... Force Quit/Wait' window. Choose the 'Force Quit' option.
3) The LinVst-X server is still running and visible in System Monitor (as expected). However if you try to launch the DAW again it simply crashes and will not open.
4) If you kill the LinVst-X process, this doesn't solve the problem - the DAW still won't relaunch. Also, if you try to restart LinVst-X by killing the process and then typing '/usr/bin/lin-vst-server-x.exe.so' in a terminal, it just says 'Segmentation fault'.
5) It seems the only way to get the DAW and LinVst-X running again is to reboot the computer.

I hope that's all clear - let me know if you need anything else!

**Comment by osxmidi** [comment]
> Hello,
> 
> I have been using LinVst-X a lot recently with some orchestral sample libraries, but have been running into the following issue...
> 
> OS: Ubuntu 20.04 DAW: Ardour 6, Reaper Plugins: Spitfire BBCSO Discover, Native Instruments Kontakt
> 
>     1. Create a project in the DAW, and load plugins via LinVst-X. Save the project.
> 
>     2. Try to close the DAW. After a few moments it crashes and displays the 'Not responding... Force Quit/Wait' window. Choose the 'Force Quit' option.
> 
>     3. The LinVst-X server is still running and visible in System Monitor (as expected). However if you try to launch the DAW again it simply crashes and will not open.
> 
>     4. If you kill the LinVst-X process, this doesn't solve the problem - the DAW still won't relaunch. Also, if you try to restart LinVst-X by killing the process and then typing '/usr/bin/lin-vst-server-x.exe.so' in a terminal, it just says 'Segmentation fault'.
> 
>     5. It seems the only way to get the DAW and LinVst-X running again is to reboot the computer.
> 
> 
> I hope that's all clear - let me know if you need anything else!

That server behaviour happens when a plugin crashes.

I'll test out Kontakt and some sample libraries and try to work out what might be going wrong and then I'll update LinVst-X.

**Comment by osxmidi** [comment]
I've updated a few things, so hopefully it will be ok.

It seems ok with Kontakt and Salamander Piano for multiple instances and exiting.

**Comment by thephantomclarinet** [comment]
Amazing, thank you! I'll give it a go later and see how I get on.

**Comment by osxmidi** [comment]
If it doesn't work let me know and I'll try some other changes.

**Comment by thephantomclarinet** [comment]
I've had a play and it seems to be working much better now. : ) Thanks again for your help!
